### ISSUE TITLE
Windows install via scoop downloads file from sourceforge that is from different repository?

### ISSUE THREAD

**Issue by janpio** [google/ios-webkit-debug-proxy#198]
I just looked into the new scoop install option for Windows, did I follow the trail correctly that this actually downloads a .zip from Souceforge that is built from the -win32 repository that was previously linked? Or was Windows support properly integrated here and I missed it somehow?

**Comment by artygus** [comment]
hi @piotrowski, now I see that it's confusing, just what @auchenberg said. Scoop build done from the current master of this project. I just had an account and already set-up project on SF for -win32 stuff, so I reused that one just because it was easier. I think I'll stick to github's release binaries thing to avoid confusion in the future

**Comment by piotrowski** [comment]
That would be great. I just wanted to make sure I understood what I actually downloaded as I haven't used scoop before. (I am probably not the only one, so manually downloading a .msi, .exe or something would be even better)

**Comment by janpio** [comment]
Any update on this?

**Comment by artygus** [comment]
hi @janpio, from now on current releases will be available from [github](https://github.com/google/ios-webkit-debug-proxy/releases) lukesampson/scoop-extras#560

**Comment by janpio** [comment]
Thanks for the update!
