### ISSUE TITLE
 ios-webkit-debug-proxy  make install error

### ISSUE THREAD

**Issue by lonelyfish** [google/ios-webkit-debug-proxy#338]
**ios 13.1.3
macos  10.14.5**

**`brew install --HEAD ios-webkit-debug-proxy`**
Updating Homebrew...
==> Cloning https://github.com/google/ios-webkit-debug-proxy.git
Updating /Users/zxc/Library/Caches/Homebrew/ios-webkit-debug-proxy--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at ba9a3f4 Merge pull request #329 from google/ios_13_support
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/ios-webkit-debug-proxy/HEAD-ba9a3f4_2
==> make install
```
Last 15 lines from /Users/zxc/Library/Logs/Homebrew/ios-webkit-debug-proxy/03.make:
clang -DHAVE_CONFIG_H -I. -I..  -I../include -I../include/ios-webkit-debug-proxy   -I/usr/local/Cellar/libplist/2.1.0/include -I/usr/local/Cellar/libusbmuxd/HEAD-53e832a_1/include -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -I/usr/local/Cellar/libimobiledevice/HEAD-7dbc17f_5/include -I/usr/local/Cellar/libplist/2.1.0/include  -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -g -O2 -Wall -Werror -c -o ios_webkit_debug_proxy-webinspector.o `test -f 'webinspector.c' || echo './'`webinspector.c
clang -DHAVE_CONFIG_H -I. -I..  -I../include -I../include/ios-webkit-debug-proxy   -I/usr/local/Cellar/libplist/2.1.0/include -I/usr/local/Cellar/libusbmuxd/HEAD-53e832a_1/include -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -I/usr/local/Cellar/libimobiledevice/HEAD-7dbc17f_5/include -I/usr/local/Cellar/libplist/2.1.0/include  -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -g -O2 -Wall -Werror -c -o ios_webkit_debug_proxy-websocket.o `test -f 'websocket.c' || echo './'`websocket.c
/bin/sh ../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I..  -I../include -I../include/ios-webkit-debug-proxy   -I/usr/local/Cellar/libplist/2.1.0/include -I/usr/local/Cellar/libusbmuxd/HEAD-53e832a_1/include -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -I/usr/local/Cellar/libimobiledevice/HEAD-7dbc17f_5/include -I/usr/local/Cellar/libplist/2.1.0/include  -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -g -O2 -Wall -Werror -c -o ios_webkit_debug_proxy_main.lo ios_webkit_debug_proxy_main.c
```
webinspector.c:58:3: error: redefinition of enumerator 'CONNECTION_USBMUXD'
  CONNECTION_USBMUXD = 1
  ^
/usr/local/Cellar/libimobiledevice/HEAD-7dbc17f_5/include/libimobiledevice/libimobiledevice.h:64:2: note: previous definition is here
        CONNECTION_USBMUXD = 1,
        ^
1 error generated.
make[1]: *** [ios_webkit_debug_proxy-webinspector.o] Error 1
make[1]: *** Waiting for unfinished jobs....

> libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I../include -I../include/ios-webkit-debug-proxy -I/usr/local/Cellar/libplist/2.1.0/include -I/usr/local/Cellar/libusbmuxd/HEAD-53e832a_1/include -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -I/usr/local/Cellar/libimobiledevice/HEAD-7dbc17f_5/include -I/usr/local/Cellar/libplist/2.1.0/include -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -g -O2 -Wall -Werror -c ios_webkit_debug_proxy_main.c  -fno-common -DPIC -o .libs/ios_webkit_debug_proxy_main.o
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I../include -I../include/ios-webkit-debug-proxy -I/usr/local/Cellar/libplist/2.1.0/include -I/usr/local/Cellar/libusbmuxd/HEAD-53e832a_1/include -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -I/usr/local/Cellar/libimobiledevice/HEAD-7dbc17f_5/include -I/usr/local/Cellar/libplist/2.1.0/include -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -g -O2 -Wall -Werror -c ios_webkit_debug_proxy_main.c -o ios_webkit_debug_proxy_main.o >/dev/null 2>&1
> make: *** [install-recursive] Error 1

**Comment by artygus** [comment]
seem there was a change in libimimobiledevice headers https://github.com/libimobiledevice/libimobiledevice/commit/5390060ec90bed0f565698a389cebc57c09c3ac8 🤔 I'll take a look in a couple of days

**Comment by lonelyfish** [comment]
> seem there was a change in libimimobiledevice headers [libimobiledevice/libimobiledevice@5390060](https://github.com/libimobiledevice/libimobiledevice/commit/5390060ec90bed0f565698a389cebc57c09c3ac8) 🤔 I'll take a look in a couple of days

OK, thank you. Waiting for your news

**Comment by artygus** [comment]
I fixed the build, but faced a new problem - can't connect to updated iOS 13 devices 🤔I've had enough with hacky workarounds and no ETA on release dates from libimobiledevice, I'll try to get rid of libimobiledevice dependancy, it'll take a couple of weeks

**Comment by vimalrajgit** [comment]
I am facing the issue during make command 

-------------------------------------------
make  all-recursive
make[1]: Entering directory '/home/vimal/ios-webkit-debug-proxy'
Making all in src
make[2]: Entering directory '/home/vimal/ios-webkit-debug-proxy/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../include/ios-webkit-debug-proxy   -I/usr/include/p11-kit-1    -g -O2 -Wall -Werror -MT webinspector.lo -MD -MP -MF .deps/webinspector.Tpo -c -o webinspector.lo webinspector.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -I../include/ios-webkit-debug-proxy -I/usr/include/p11-kit-1 -g -O2 -Wall -Werror -MT webinspector.lo -MD -MP -MF .deps/webinspector.Tpo -c webinspector.c  -fPIC -DPIC -o .libs/webinspector.o
webinspector.c:95:32: error: field ‘type’ has incomplete type
   enum idevice_connection_type type;
                                ^~~~
webinspector.c: In function ‘idevice_connection_get_ssl_session’:
webinspector.c:117:24: error: ‘CONNECTION_USBMUXD’ undeclared (first use in this function)
   if (!c || c->type != CONNECTION_USBMUXD || c->data <= 0) {
                        ^~~~~~~~~~~~~~~~~~
webinspector.c:117:24: note: each undeclared identifier is reported only once for each function it appears in
Makefile:569: recipe for target 'webinspector.lo' failed
make[2]: *** [webinspector.lo] Error 1
make[2]: Leaving directory '/home/vimal/ios-webkit-debug-proxy/src'
Makefile:405: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/vimal/ios-webkit-debug-proxy'
Makefile:337: recipe for target 'all' failed
make: *** [all] Error 2
--------------------------------

**Comment by emimarz** [comment]
same here make error with ubuntu 18.04

webinspector.c:95:32: error: field ‘type’ has incomplete type
   enum idevice_connection_type type;
                                ^~~~
webinspector.c: In function ‘idevice_connection_get_ssl_session’:
webinspector.c:117:24: error: ‘CONNECTION_USBMUXD’ undeclared (first use in this function)
   if (!c || c->type != CONNECTION_USBMUXD || c->data <= 0) {

**Comment by artygus** [comment]
@emimarz check out closed issues, e.g. #341

**Comment by ElielCohen** [comment]
> I fixed the build, but faced a new problem - can't connect to updated iOS 13 devices 🤔I've had enough with hacky workarounds and no ETA on release dates from libimobiledevice, I'll try to get rid of libimobiledevice dependancy, it'll take a couple of weeks

Any news ?
I am not facing issue building the tools, but I'm facing a crash of iOS-webkit-debug-proxy when trying to inject javascript files on iOS13 devices (on hybrid apps).

Here is the error that is returned when it crashes : 
Connected :28527 to iPhone 11 Pro (00008030-000C0CA10100802E)
Taking page 28527/1 from local FD445751-891B-4525-BF53-64D71B251F86 to B2EE24EA-203D-413E-B3FF-A83A81D906C6
ssl sendq retry failed: Undefined error: 0
Disconnected :28527 from iPhone 11 Pro (00008030-000C0CA10100802E)

I've checked the error code (1), it's the error for general SSL ERROR.

I suspect that since iOS 13 is requiring more secure SSL TLS communication, it is linked to the fact that the actual implementation of ios_webkit_debug_proxy is not supporting GNUTLS, but I may be wrong :)

Hope to hear news from you soon, and thanks for your amazing work :)

**Comment by artygus** [comment]
@ElielCohen only ssl is supported

**Comment by ElielCohen** [comment]
> @ElielCohen currently only libssl is supported, i.e. libimobiledevice has to be built with libssl support

I tried it using libimobildevice from brew, using the --HEAD flag, and it still crashes in the same manor when injecting JS.

Is the version provided by brew is built with libssl support ?

**Comment by nanna481** [comment]
> **ios 13.1.3 macos 10.14.5**
> 
> **`brew install --HEAD ios-webkit-debug-proxy`**
> Updating Homebrew...
> ==> Cloning https://github.com/google/ios-webkit-debug-proxy.git
> Updating /Users/zxc/Library/Caches/Homebrew/ios-webkit-debug-proxy--git
> ==> Checking out branch master
> Already on 'master'
> Your branch is up to date with 'origin/master'.
> HEAD is now at [ba9a3f4](https://github.com/google/ios-webkit-debug-proxy/commit/ba9a3f463dd4a741523afd3706b39ba6c2a7907b) Merge pull request #329 from google/ios_13_support
> ==> ./autogen.sh
> ==> ./configure --prefix=/usr/local/Cellar/ios-webkit-debug-proxy/HEAD-ba9a3f4_2
> ==> make install
> 
> ```
> Last 15 lines from /Users/zxc/Library/Logs/Homebrew/ios-webkit-debug-proxy/03.make:
> clang -DHAVE_CONFIG_H -I. -I..  -I../include -I../include/ios-webkit-debug-proxy   -I/usr/local/Cellar/libplist/2.1.0/include -I/usr/local/Cellar/libusbmuxd/HEAD-53e832a_1/include -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -I/usr/local/Cellar/libimobiledevice/HEAD-7dbc17f_5/include -I/usr/local/Cellar/libplist/2.1.0/include  -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -g -O2 -Wall -Werror -c -o ios_webkit_debug_proxy-webinspector.o `test -f 'webinspector.c' || echo './'`webinspector.c
> clang -DHAVE_CONFIG_H -I. -I..  -I../include -I../include/ios-webkit-debug-proxy   -I/usr/local/Cellar/libplist/2.1.0/include -I/usr/local/Cellar/libusbmuxd/HEAD-53e832a_1/include -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -I/usr/local/Cellar/libimobiledevice/HEAD-7dbc17f_5/include -I/usr/local/Cellar/libplist/2.1.0/include  -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -g -O2 -Wall -Werror -c -o ios_webkit_debug_proxy-websocket.o `test -f 'websocket.c' || echo './'`websocket.c
> /bin/sh ../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I..  -I../include -I../include/ios-webkit-debug-proxy   -I/usr/local/Cellar/libplist/2.1.0/include -I/usr/local/Cellar/libusbmuxd/HEAD-53e832a_1/include -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -I/usr/local/Cellar/libimobiledevice/HEAD-7dbc17f_5/include -I/usr/local/Cellar/libplist/2.1.0/include  -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -g -O2 -Wall -Werror -c -o ios_webkit_debug_proxy_main.lo ios_webkit_debug_proxy_main.c
> ```
> 
> webinspector.c:58:3: error: redefinition of enumerator 'CONNECTION_USBMUXD'
> CONNECTION_USBMUXD = 1
> ^
> /usr/local/Cellar/libimobiledevice/HEAD-7dbc17f_5/include/libimobiledevice/libimobiledevice.h:64:2: note: previous definition is here
> CONNECTION_USBMUXD = 1,
> ^
> 1 error generated.
> make[1]: *** [ios_webkit_debug_proxy-webinspector.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> 
> > libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I../include -I../include/ios-webkit-debug-proxy -I/usr/local/Cellar/libplist/2.1.0/include -I/usr/local/Cellar/libusbmuxd/HEAD-53e832a_1/include -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -I/usr/local/Cellar/libimobiledevice/HEAD-7dbc17f_5/include -I/usr/local/Cellar/libplist/2.1.0/include -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -g -O2 -Wall -Werror -c ios_webkit_debug_proxy_main.c  -fno-common -DPIC -o .libs/ios_webkit_debug_proxy_main.o
> > libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I../include -I../include/ios-webkit-debug-proxy -I/usr/local/Cellar/libplist/2.1.0/include -I/usr/local/Cellar/libusbmuxd/HEAD-53e832a_1/include -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -I/usr/local/Cellar/libimobiledevice/HEAD-7dbc17f_5/include -I/usr/local/Cellar/libplist/2.1.0/include -I/usr/local/Cellar/openssl@1.1/1.1.1d/include -g -O2 -Wall -Werror -c ios_webkit_debug_proxy_main.c -o ios_webkit_debug_proxy_main.o >/dev/null 2>&1
> > make: *** [install-recursive] Error 1

**Comment by amitrparmar** [comment]
I am also facing the same issue. Could someone please suggest. I am using below environment.

appium - 1.16.0-beta.1
npm - 6.12.1
node - 12.12.0
Java - openJDK '13'
Xcode - 11.1
MAC - macOS Cataline
platform - iPad (iOS v. 13) (Real Device)

**Comment by ramaninaresh** [comment]
I am also getting the same issue in IOS13.x.
appium - 1.16.0-beta.1
npm - 6.12.1
node - 12.12.0
Java - openJDK '13'
Xcode - 11.1
MAC - macOS Cataline
platform - iPad (iOS v. 13) (Real Device)

Please help on this issue

**Comment by artygus** [comment]
@ramaninaresh I don't think appium 1.16.0 uses this utility appium/appium#13368

**Comment by ashu123mae** [comment]
Getting error -  
**Installing ios-webkit-debug-proxy --HEAD**
==> Cloning https://github.com/google/ios-webkit-debug-proxy.git
Cloning into '/Users/tritesh/Library/Caches/Homebrew/ios-webkit-debug-proxy--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/ios-webkit-debug-proxy/HEAD-7496519
==> make install
🍺  /usr/local/Cellar/ios-webkit-debug-proxy/HEAD-7496519: 13 files, 342.3KB, built in 56 seconds
==> `brew cleanup` has not been run in 30 days, running now...
Removing: /Users/tritesh/Library/Caches/Homebrew/carthage--0.33.0.high_sierra.bottle.tar.gz... (7.0MB)
Removing: /Users/tritesh/Library/Caches/Homebrew/icu4c--64.2.mojave.bottle.tar.gz... (26.1MB)
Removing: /Users/tritesh/Library/Caches/Homebrew/ideviceinstaller--1.1.0_4.mojave.bottle.tar.gz... (22.3KB)
Removing: /usr/local/Cellar/libimobiledevice/1.2.0_4... (66 files, 1MB)
Removing: /Users/tritesh/Library/Caches/Homebrew/libimobiledevice--1.2.0_4.mojave.bottle.tar.gz... (279.2KB)
Removing: /usr/local/Cellar/libplist/2.0.0_1... (29 files, 345.7KB)
Removing: /Users/tritesh/Library/Caches/Homebrew/libplist--2.0.0_1.mojave.bottle.tar.gz... (107.5KB)
Removing: /usr/local/Cellar/libtasn1/4.14... (59 files, 384KB)
Removing: /Users/tritesh/Library/Caches/Homebrew/libtasn1--4.14.mojave.bottle.tar.gz... (120.4KB)
Removing: /Users/tritesh/Library/Caches/Homebrew/libusb--1.0.23.mojave.bottle.tar.gz... (168.4KB)
Removing: /usr/local/Cellar/libusbmuxd/1.0.10_1... (13 files, 120KB)
Removing: /Users/tritesh/Library/Caches/Homebrew/libzip--1.5.2.mojave.bottle.1.tar.gz... (113.1KB)
Removing: /Users/tritesh/Library/Caches/Homebrew/node--12.11.1.mojave.bottle.tar.gz... (14.8MB)
Removing: /usr/local/Cellar/openssl@1.1/1.1.1d... (7,983 files, 17.9MB)
Removing: /Users/tritesh/Library/Caches/Homebrew/openssl@1.1--1.1.1d.mojave.bottle.tar.gz... (5.2MB)
Removing: /Users/tritesh/Library/Caches/Homebrew/usbmuxd--1.0.10_1.mojave.bottle.tar.gz... (38.8KB)
Removing: /Users/tritesh/Library/Caches/Homebrew/Cask/adoptopenjdk8--8,222:b10.pkg... (97.8MB)
Removing: /Users/tritesh/Library/Logs/Homebrew/libimobiledevice... (64B)
Removing: /Users/tritesh/Library/Logs/Homebrew/libplist... (64B)
Removing: /Users/tritesh/Library/Logs/Homebrew/icu4c... (64B)
Removing: /Users/tritesh/Library/Logs/Homebrew/carthage... (64B)
Removing: /Users/tritesh/Library/Logs/Homebrew/ideviceinstaller... (64B)
Removing: /Users/tritesh/Library/Logs/Homebrew/libtasn1... (64B)
Removing: /Users/tritesh/Library/Logs/Homebrew/openssl@1.1... (64B)
Removing: /Users/tritesh/Library/Logs/Homebrew/usbmuxd... (64B)
Removing: /Users/tritesh/Library/Logs/Homebrew/node... (64B)
Removing: /Users/tritesh/Library/Logs/Homebrew/libzip... (64B)
Removing: /Users/tritesh/Library/Logs/Homebrew/libusb... (64B)
Pruned 0 symbolic links and 2 directories from /usr/local
`Error: Permission denied @ apply2files - /usr/local/lib/node_modules/webpack/node_modules/timers-browserify/.DS_Store`
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC.

**Comment by sylvain-farnault** [comment]
`make` error on Ubuntu 18
![Capture d’écran de 2020-06-15 16-09-26](https://user-images.githubusercontent.com/59399139/84668450-f194d300-af23-11ea-8186-b6bd4ad2511d.png)

**Comment by artygus** [comment]
fixed by https://github.com/google/ios-webkit-debug-proxy/commit/d02ed217f5b756cefc65495e83b107d7efd75e4d, new version has been published to brew https://github.com/Homebrew/homebrew-core/pull/57426. HEAD flag is not required anymore, since new version of libimobiledevice has been officially released
