### ISSUE TITLE
Could not start com.apple.webinspector

### ISSUE THREAD

**Issue by mikeatlas** [google/ios-webkit-debug-proxy#61]
I ran: 

`$brew install ios-webkit-debug-proxy`
`/usr/local/Cellar/ios-webkit-debug-proxy/1.3: 15 files, 164K, built in 16 seconds`

Then I ran:

`$ios_webkit_debug_proxy`
`Could not start com.apple.webinspector!: Undefined error: 0`
`Unable to attach 52cd3d70d9800959254b37468560c770fe2a181a inspector`

My software versions:
XCode 5.1.1 (5B1008)
OS X 10.9.3
Safari 7.0.4 (9537.76.4) (on my computer)
iPhone 5
iOS 7.1.1 (11D201)

For what it's worth, I'm able to use Safari Web Inspector to debug iOS Safari via my desktop web inspector without a problem. Any tips?

**Comment by trevor403** [comment]
I have the same problem on Ubuntu 14.04

**Comment by en90** [comment]
I had a similar problem on Fedora 23 and after some reading I figured it might be due to the version of libimobiledevice installed by dnf being a bit too old. I built libimobiledevice from source https://github.com/libimobiledevice/libimobiledevice and then I rebuilt ios-webkit-debug-proxy as follows so as not to use the libimobiledevice version installed by dnf (which I keep because removing it would also remove a bunch of other stuff):

```bash
make clean
make distclean
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/ ./autogen.sh 
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/ make
sudo make install
```

ios-webkit-debug-proxy seems to be at least partly working now.
