### ISSUE TITLE
Doesn't support iOS 8.1 on Ubuntu 14.10

### ISSUE THREAD

**Issue by octoxan** [google/ios-webkit-debug-proxy#82]
Gives the error
could not start com.apple.webinspector! success
unable to attach _________ inspector

**Comment by Afforess** [comment]
I had the same problem. I did debugging and it appears to be a problem with the way libimobiledevice is packaged on Ubuntu (I am on 14.10). I removed the package and compiled libimobiledevice from source and the problem went away.

**Comment by tmeloliveira** [comment]
Hi @Afforess, 
I'm still facing the issue, would you be able to share some details of your solution ?

**Comment by Afforess** [comment]
@tmeloliveira You have to remove the libimobiledevice package, so apt-get purge libimobiledevice*

To make sure it is removed properly, try starting ios-webkit-debug-proxy, it should crash, as it is missing the dependency. If it crashes, continue:

Then clone the project from here: https://github.com/libimobiledevice/libimobiledevice

Follow their steps to install. It should install the binaries in /usr/local/lib

Symlink the binaries from /usr/local/lib to /usr/lib and try starting the ios-webkit-debug-proxy again.

**Comment by tommyJS** [comment]
The comment of @Afforess is [marked](https://github.com/google/ios-webkit-debug-proxy#could-not-start-comapplewebinspector-success) as the solution, however, it does not work in my case.
I invoked `apt-get purge libimobiledevice*` both in Linux Mint Rosa 17.3 and Ubuntu LTS 16.04.  In these systems the result was that I could not login to my system once again - some stuff regarding gnome session was deleted during purging, for instance, `gnome-session` package. Do you know how to prevent that?

**Comment by Afforess** [comment]
@tommyJS sounds like it purged the entire desktop set of packages, which is bad.

I haven't  tried this in a little while. Looking back at what I remember, I think you could get away with leaving the package installed, but overwriting the binaries in /usr/lib with compiled copies. This is sort of a bad practice, but so is packaging libimobiledevice wrong...

I really can't give any better advice off the top of my head. I'll spin up a VM and see if I can toy around with this again. It might have even been fixed in 16.04, who knows.

**Comment by tommyJS** [comment]
@Afforess, thank you. You are right that I cannot purge libimobiledevice, because it deletes the entire desktop set of packages and you are right that symlinking binaries from `/usr/local/lib` to `/usr/lib` resolves the problem.

However, applying this solution causes [this problem](https://github.com/google/ios-webkit-debug-proxy#could-not-connect-to-lockdownd). I trusted the device a few times and nothing works.
Version of iOS: `8.1.2 (12B440)`. Any ideas?

**Comment by Afforess** [comment]
@tommyJS thanks for the update. I edited my previous comment and removed the steps involving purging libimobiledevice, hopefully that prevents future users from falling into the same trap you did.

I didn't see any issues with lockdownd when I did this, but that was because my device was configured without a passcode or touch id. I would suggest disabling both and trying again.

**Comment by df257** [comment]
Hello, how to remove and rebuild libimobiledevice on window10?
