### ISSUE TITLE
Library not loaded: /usr/local/lib/libimobiledevice.5.dylib when starting ios_webkit_debug_proxy

### ISSUE THREAD

**Issue by kani19** [google/ios-webkit-debug-proxy#90]
I am getting this error when starting ios_webkit_debug_proxy. Have tried installing and linking again but its not working.

ios_webkit_debug_proxy -c c88361f2aaea4c0fad53e208fe55981c3a900eb3:27753 -d &
[2] 15476
dyld: Library not loaded: /usr/local/lib/libimobiledevice.5.dylib
  Referenced from: /usr/local/bin/ios_webkit_debug_proxy
  Reason: image not found

[2]+  Trace/BPT trap: 5       ios_webkit_debug_proxy -c c88361f2aaea4c0fad53e208fe55981c3a900eb3:27753 -d

**Comment by amarnathrayudu** [comment]
Hi @kani19,

I had the same issue and it is fixed with this below steps.

1. brew doctor
 expected : Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

    ios-webkit-debug-proxy

2.  brew link ios-webkit-debug-proxy

Note : do a force link if you see the warning.

3. try launching proxy now.

Thanks,
Amarnath Rayudu

**Comment by paulirish** [comment]
thanks for the help Amarnath!

**Comment by ygalbel** [comment]
Thank for help.

In my case, missing links was
    libimobiledevice
    libplist
    libtasn1
    libusb
    usbmuxd

after manual link, debugger work fine.
