### ISSUE TITLE
Please merge James Chuong's fork to Handle the "_rpc_applicationUpdated" message

### ISSUE THREAD

**Issue by ChuanyuWang** [google/ios-webkit-debug-proxy#96]
Hi Admin,

As upgrade to iOS 8.1+, iOS-webkit-debug-proxy disconnect device during running. Because one new message "_rpc_applicationUpdated" is not handled correctly. The fix have been submitted into a folk repository - https://github.com/jchuong/ios-webkit-debug-proxy. Would you please merge the fix for the iOS users? 

Thanks,
Chuanyu

**Comment by ChuanyuWang** [comment]
It took me almost a week to get it through on iOS 8.3, I put more investigation result at [iOS 8.3 unknown app ID](https://github.com/jchuong/ios-webkit-debug-proxy/issues/1). If you are still looking for it, please come and contribute.

**Comment by lzbob** [comment]
Vote + 1, we are currently waiting for the fix, otherwise, can't test mobile safari on iOS 8 device.

**Comment by wrightt** [comment]
Sounds good to me.  I'll email @jchuong and ask him to submit a pull request.

**Comment by ChuanyuWang** [comment]
@wrightt We have forked the repository from google, and try to fix the issue as jchuong is busy. Back to you when we get more progress.

**Comment by jchuong** [comment]
Just a quick update since I went dark for 2 weeks.. I moved last week and this week and I don't currently have my work laptop or devices so I haven't been able to check out the necessary steps to fix these new keys.

**Comment by wrightt** [comment]
@jchuong, I've added you as a project collaborator, so please feel free to submit when ready.

**Comment by chris1248** [comment]
Vote +1 here too. We are also experiencing an issue with that on IOS 8.3. As a result, we cannot test on a real IPad or IPhone yet.

**Comment by jchuong** [comment]
I have made the pull request and merged it.  Please try it out, though I don't think 8.3 will actually work just yet due to the new changes.  You may be adventurous and try out https://github.com/jchuong/ios-webkit-debug-proxy/pull/2 which basically disables all error messages.  I believe this is hacky and isn't the right solution but if you're tired of chasing tails after every update to iOS, it will be a bandaid fix.  I will close this now, please reopen if something horribly went wrong with my PR (not used to doing this...also upstream became updated and my commits were a mess).
